#!/usr/bin/env python
#
# Copyright (c) 2014 CERN
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

from __future__ import print_function

import argparse
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
import sys

from colorama import Fore, Style
from datetime import datetime
from prettytable import PrettyTable
from sqlalchemy import and_, create_engine, func, MetaData, select, Table
from sqlalchemy.orm import sessionmaker


class project_resource_usage(object):
    def __init__(self, project_id, user_id):
        self.project_id = project_id
        self.user_id = user_id
        self.qu = {
            'instances': 0,
            'cores': 0,
            'ram': 0,
            'security_groups': 0,
            'server_groups': 0,
            'floating_ips': 0}
        self.nu = {
            'instances': 0,
            'cores': 0,
            'ram': 0}
        self.in_sync = True
        self.status = 'OK'

    def update_quota_usage(self, resource, value):
        self.qu[resource] = value

    def update_nova_usage(self, instances, cores, ram):
        self.nu['instances'] = instances
        self.nu['cores'] = cores
        self.nu['ram'] = ram

    def update_sync_status(self):
        for resource in ['instances', 'cores', 'ram']:
            if self.nu[resource] != self.qu[resource]:
                self.in_sync = False
                self.status = 'Mismatch'


def sql_connect(db_url, debug):
    engine = create_engine(db_url, echo=debug)
    conn = engine.connect()
    sessionmaker(bind=engine)
    meta = MetaData()
    meta.bind = engine
    return conn, meta


def sql_disconnect(conn):
    conn.close()


def update_quota_usages(meta, usage):
    for resource in usage.nu:
        if resource != usage.qu[resource]:
            update_quota_usages_db(meta,
                                   usage.project_id,
                                   usage.user_id,
                                   resource,
                                   usage.qu.resource)
            usage.status = 'Fixed'


def update_quota_usages_db(meta, project_id, user_id, resource, in_use):
    quota_usages = Table('quota_usages', meta, autoload=True)
    now = datetime.utcnow()
    quota = select(
        columns=[quota_usages.c.user_id],
        whereclause=and_(quota_usages.c.user_id == user_id,
                         quota_usages.c.project_id == project_id,
                         quota_usages.c.resource == resource)
                  ).execute().fetchone()

    if not quota:
        quota_usages.insert().values(
            created_at=now,
            updated_at=now,
            project_id=project_id,
            resource=resource,
            in_use=in_use,
            reserved=0,
            deleted=0,
            user_id=user_id).execute()
    else:
        quota_usages.update().where(
            and_(
                quota_usages.c.user_id == user_id,
                quota_usages.c.project_id == project_id,
                quota_usages.c.resource == resource
                )
            ).values(updated_at=now, in_use=in_use).execute()


def display(resources_usage, all_resources=False):
    ptable = PrettyTable(['Project ID',
                          'User ID',
                          'Instances',
                          'Cores',
                          'Ram',
                          'Status'])

    for usage in resources_usage:
        if not usage.in_sync:
            if usage.nu['instances'] != usage.qu['instances']:
                instances = str(usage.qu['instances']) + ' -> ' + \
                    str(usage.nu['instances'])
            else:
                instances = usage.nu['instances']
            if usage.nu['cores'] != usage.qu['cores']:
                cores = str(usage.qu['cores']) + ' -> ' + \
                    str(usage.nu['cores'])
            else:
                cores = usage.nu['cores']
            if usage.nu['ram'] != usage.qu['ram']:
                ram = str(usage.qu['ram']) + ' -> ' + str(usage.nu['ram'])
            else:
                ram = usage.nu['ram']

            ptable.add_row([usage.project_id,
                            usage.user_id,
                            instances,
                            cores,
                            ram,
                            Fore.RED + usage.status + Style.RESET_ALL])
        else:
            if all_resources:
                ptable.add_row([usage.project_id,
                                usage.user_id,
                                usage.nu['instances'],
                                usage.nu['cores'],
                                usage.nu['ram'],
                                Fore.GREEN + usage.status + Style.RESET_ALL])
    print(ptable)


def get_resource_usage(meta, project=None):
    resource_usage = []

    if project is None:
        projects_q = query_projects_using_quota(meta)
    else:
        projects_q = query_projects_using_quota(meta, project)

    all_instances_q = query_instances(meta)
    all_quota_usages_q = query_quota_usages(meta)

    for project_id, user_id in projects_q:
        if user_id is None:
            text = '[Warning] Project {0} '.format(project_id)
            text += 'has resources belonging to a non-existent user'
            print(text)
            continue

        usage = project_resource_usage(project_id, user_id)

        quota_usages_q = [x for x in all_quota_usages_q if
                          x['project_id'] == project_id and
                          x['user_id'] == user_id]
        for _, _, resource, value in quota_usages_q:
            usage.update_quota_usage(resource, value)

        nova_usages_q = [x for x in all_instances_q if
                         x['project_id'] == project_id and
                         x['user_id'] == user_id]
        for _, _, instances, cores, ram in nova_usages_q:
            usage.update_nova_usage(instances, cores, ram)

        usage.update_sync_status()
        resource_usage.append(usage)

    return resource_usage


def query_projects_using_quota(meta, project_id=None):
    quota_usages = Table('quota_usages', meta, autoload=True)

    q = select(
        columns=[
            quota_usages.c.project_id,
            quota_usages.c.user_id])

    if project_id is not None:
        q = q.where(quota_usages.c.project_id == project_id)

    q = q.group_by(
        quota_usages.c.project_id,
        quota_usages.c.user_id)

    return q.execute().fetchall()


def query_instances(meta):
    instances = Table('instances', meta, autoload=True)

    q = select(
        columns=[
            instances.c.project_id,
            instances.c.user_id,
            func.count(instances.c.id).label('instances'),
            func.sum(instances.c.vcpus).label('cores'),
            func.sum(instances.c.memory_mb).label('ram')])

    q = q.where(instances.c.deleted == 0)

    q = q.group_by(
        instances.c.project_id,
        instances.c.user_id)

    return q.execute().fetchall()


def query_quota_usages(meta):
    quota_usages = Table('quota_usages', meta, autoload=True)

    q = select(
        columns=[
            quota_usages.c.project_id,
            quota_usages.c.user_id,
            quota_usages.c.resource,
            func.sum(quota_usages.c.in_use).label('in_use')])

    q = q.where(quota_usages.c.deleted == 0)

    q = q.group_by(
        quota_usages.c.project_id,
        quota_usages.c.user_id,
        quota_usages.c.resource)

    return q.execute().fetchall()


def sync_resource_usage(meta, resource_usage):
    for usage in resource_usage:
        if not usage.in_sync:
            update_quota_usages(meta, usage)


def get_nova_db_url(config_file):
    parser = configparser.SafeConfigParser()
    try:
        parser.read(config_file)
        nova_db_url = parser.get('database', 'connection')
    except Exception as e:
        text = '[Error] cannot parse nova configuration file: {0}'.format(e)
        print(text)
        sys.exit(2)
    return nova_db_url


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-a', '--all',
        action='store_true',
        default=False,
        help='show the state of all quota resources')
    parser.add_argument(
        '-s', '--sync',
        action='store_true',
        default=False,
        help='perform synchronization of mismatched resources')
    parser.add_argument(
        '-p', '--project',
        type=str,
        help='operate only on this project ID')
    parser.add_argument(
        '-c', '--config',
        default='/etc/nova/nova.conf',
        help='path to nova configuration file')
    parser.add_argument(
        '-d', '--debug',
        action='store_true',
        default=False,
        help='enable debug mode')
    return parser.parse_args()


def main():
    args = parse_args()
    nova_db_url = get_nova_db_url(args.config)
    conn, meta = sql_connect(nova_db_url, args.debug)
    resource_usage = get_resource_usage(meta, args.project)
    if args.sync:
        sync_resource_usage(meta, resource_usage)
    display(resource_usage, args.all)
    sql_disconnect(conn)


if __name__ == '__main__':
    main()
